apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
  namespace: ha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: ha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 192.168.1.1
          - 1.1.1.1
        options:
          - name: ndots
            value: "1"
      containers:
      - name: homeassistant
        image: ghcr.io/tommyzam/homeassistant-ca:stable
        ports:
        - containerPort: 8123
        env:
        - name: TZ
          value: Pacific/Honolulu
        - name: SSL_CERT_FILE
          value: /etc/ssl/cert.pem
        - name: SSL_CERT_DIR
          value: /etc/ssl/certs
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homeassistant-config
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: ha
spec:
  selector:
    app: homeassistant
  ports:
  - name: http
    port: 8123
    targetPort: 8123
